"""Frigate, the recording half of Phase 4 (SPEC.md 37).

Frigate is config-file driven, so its config is *generated* from the cameras in the
device registry rather than hand-written. Adding a camera in the UI and pressing
"apply" rewrites the file; Frigate reloads cameras on restart, which is the one bit
of this that cannot be done from the browser alone.

Detection runs on the CPU by Santiago's decision: the 3060 Ti's 8 GB is already
split between the language model, Whisper and the vision model, and continuous
detection on top of that would change the budget every earlier phase was tuned
around.
"""
import asyncio
import json
import os
import re
from pathlib import Path

import httpx
from fastapi import APIRouter, Depends

import auth
import cameras
import registry
import settings

CONFIG_PATH = Path(os.environ.get("FRIGATE_CONFIG", "/frigate/config.yml"))
FRIGATE_URL = os.environ.get("FRIGATE_URL", "http://frigate:5000")
MQTT_HOST = os.environ.get("MQTT_HOST", "mqtt")

router = APIRouter(prefix="/frigate", tags=["cameras"])

settings.setting(
    "frigate.record_days", type="integer", minimum=0, maximum=90, default=7,
    title="Keep recordings for (days)",
    description="Continuous recording is the largest thing IRiS stores. 0 records "
                "nothing and keeps only clips of detected events.")
settings.setting(
    "frigate.detect_fps", type="integer", minimum=1, maximum=15, default=5,
    title="Detection frame rate",
    description="Frames a second put through object detection. On CPU this is the "
                "setting that decides how much of the machine Frigate takes.")
settings.setting(
    "frigate.objects", type="string", default="person,car,dog,cat",
    title="What to detect",
    description="Comma-separated. Fewer objects is faster; 'person' alone is usually "
                "what matters.")


def slug(name: str) -> str:
    """Frigate camera keys must be identifier-safe; 'front door' is not."""
    return re.sub(r"[^a-z0-9_]+", "_", name.strip().lower()).strip("_") or "camera"


async def probe(url: str) -> tuple[int, int]:
    """Ask the stream its own resolution rather than guessing.

    Frigate wants detect width and height, and a wrong guess either crops the frame
    or wastes CPU scaling it.
    """
    transport = ["-rtsp_transport", "tcp"] if url.startswith("rtsp") else []
    proc = await asyncio.create_subprocess_exec(
        "ffprobe", "-v", "error", *transport, "-select_streams", "v:0",
        "-show_entries", "stream=width,height", "-of", "json", url,
        stdout=asyncio.subprocess.PIPE, stderr=asyncio.subprocess.PIPE)
    try:
        out, _ = await asyncio.wait_for(proc.communicate(), 25)
        stream = (json.loads(out).get("streams") or [{}])[0]
        return int(stream["width"]), int(stream["height"])
    except Exception:
        # An offline camera is the common case here, not the rare one, and by then
        # ffprobe has usually already exited: killing it again raises.
        if proc.returncode is None:
            try:
                proc.kill()
            except ProcessLookupError:
                pass
        return 1280, 720          # a sane default beats refusing to write a config


def _yaml(value) -> str:
    """Enough YAML for this file. A camera URL can contain anything, so it is always
    quoted and its quotes escaped."""
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, int):
        return str(value)
    return '"' + str(value).replace("\\", "\\\\").replace('"', '\\"') + '"'


async def build_config() -> str:
    cams = await registry.enabled_of_type("device", "camera")
    objects = [o.strip() for o in settings.get("frigate.objects").split(",")
               if o.strip()]
    days = settings.get("frigate.record_days")
    fps = settings.get("frigate.detect_fps")

    lines = [
        "# Generated by IRiS from the cameras in Settings > Devices.",
        "# Edits here are overwritten. Change cameras in the UI instead.",
        "mqtt:",
        f"  host: {MQTT_HOST}",
        "  topic_prefix: frigate",
        "",
        "detectors:",
        "  cpu1:",
        "    type: cpu",
        "",
        "objects:",
        "  track:",
    ]
    lines += [f"    - {o}" for o in objects] or ["    - person"]
    lines += [
        "",
        "record:",
        "  enabled: " + ("true" if days else "false"),
        "  retain:",
        f"    days: {days}",
        "    mode: motion",
        "",
        "snapshots:",
        "  enabled: true",
        "  retain:",
        "    default: 14",
        "",
        "cameras:",
    ]
    if not cams:
        # Frigate refuses to start with no cameras, so an empty config is not a
        # valid one. The service simply does not run until there is a camera.
        return ""
    for cam in cams:
        url = cam["config"].get("url", "")
        width, height = await probe(url)
        lines += [
            f"  {slug(cam['name'])}:",
            "    ffmpeg:",
            "      inputs:",
            f"        - path: {_yaml(url)}",
            "          roles:",
            "            - detect",
            "            - record",
            "    detect:",
            f"      width: {width}",
            f"      height: {height}",
            f"      fps: {fps}",
        ]
    return "\n".join(lines) + "\n"


async def apply() -> dict:
    text = await build_config()
    cams = await registry.enabled_of_type("device", "camera")
    if not text:
        return {"written": False, "cameras": 0,
                "detail": "No cameras yet. Frigate needs at least one to start."}
    CONFIG_PATH.parent.mkdir(parents=True, exist_ok=True)
    CONFIG_PATH.write_text(text)
    return {"written": True, "cameras": len(cams), "path": str(CONFIG_PATH),
            "detail": "Config written. Start or restart Frigate to pick it up: "
                      "docker compose --profile cameras up -d frigate"}


async def status() -> dict:
    try:
        async with httpx.AsyncClient(timeout=5) as c:
            r = await c.get(f"{FRIGATE_URL}/api/stats")
        return {"running": r.status_code == 200}
    except Exception:
        return {"running": False}


@router.get("")
async def get_status(_: dict = Depends(auth.require_role("creator", "admin"))):
    cams = await registry.enabled_of_type("device", "camera")
    return {**await status(), "cameras": len(cams),
            "config_exists": CONFIG_PATH.exists()}


@router.post("/apply")
async def write_config(_: dict = Depends(auth.require_role("creator", "admin"))):
    return await apply()


@router.get("/config")
async def preview(_: dict = Depends(auth.require_role("creator", "admin"))):
    return {"config": await build_config()}
